# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sds_removal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sds_removal.proto',
  package='sds_removal',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11sds_removal.proto\x12\x0bsds_removal\"\x1a\n\x07Request\x12\x0f\n\x07ndarray\x18\x01 \x01(\x0c\"?\n\x08Response\x12\x11\n\tndarray_r\x18\x01 \x01(\x0c\x12\x11\n\tndarray_p\x18\x02 \x01(\x0c\x12\r\n\x05score\x18\x03 \x01(\x02\x32\x45\n\x07Remover\x12:\n\tinference\x12\x14.sds_removal.Request\x1a\x15.sds_removal.Response\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='sds_removal.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ndarray', full_name='sds_removal.Request.ndarray', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=60,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='sds_removal.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ndarray_r', full_name='sds_removal.Response.ndarray_r', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ndarray_p', full_name='sds_removal.Response.ndarray_p', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='sds_removal.Response.score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'sds_removal_pb2'
  # @@protoc_insertion_point(class_scope:sds_removal.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'sds_removal_pb2'
  # @@protoc_insertion_point(class_scope:sds_removal.Response)
  ))
_sym_db.RegisterMessage(Response)



_REMOVER = _descriptor.ServiceDescriptor(
  name='Remover',
  full_name='sds_removal.Remover',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=127,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='inference',
    full_name='sds_removal.Remover.inference',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOVER)

DESCRIPTOR.services_by_name['Remover'] = _REMOVER

# @@protoc_insertion_point(module_scope)
