# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sds_image_matching.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sds_image_matching.proto',
  package='sds_image_matching',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18sds_image_matching.proto\x12\x12sds_image_matching\"?\n\x15ImageMatching_Request\x12\x11\n\tfarImages\x18\x01 \x03(\x0c\x12\x13\n\x0b\x63loseImages\x18\x02 \x03(\x0c\"(\n\x16ImageMatching_Response\x12\x0e\n\x06result\x18\x01 \x01(\t2u\n\rImageMatching\x12\x64\n\tinference\x12).sds_image_matching.ImageMatching_Request\x1a*.sds_image_matching.ImageMatching_Response\"\x00\x62\x06proto3')
)




_IMAGEMATCHING_REQUEST = _descriptor.Descriptor(
  name='ImageMatching_Request',
  full_name='sds_image_matching.ImageMatching_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='farImages', full_name='sds_image_matching.ImageMatching_Request.farImages', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='closeImages', full_name='sds_image_matching.ImageMatching_Request.closeImages', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=111,
)


_IMAGEMATCHING_RESPONSE = _descriptor.Descriptor(
  name='ImageMatching_Response',
  full_name='sds_image_matching.ImageMatching_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='sds_image_matching.ImageMatching_Response.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['ImageMatching_Request'] = _IMAGEMATCHING_REQUEST
DESCRIPTOR.message_types_by_name['ImageMatching_Response'] = _IMAGEMATCHING_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageMatching_Request = _reflection.GeneratedProtocolMessageType('ImageMatching_Request', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEMATCHING_REQUEST,
  __module__ = 'sds_image_matching_pb2'
  # @@protoc_insertion_point(class_scope:sds_image_matching.ImageMatching_Request)
  ))
_sym_db.RegisterMessage(ImageMatching_Request)

ImageMatching_Response = _reflection.GeneratedProtocolMessageType('ImageMatching_Response', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEMATCHING_RESPONSE,
  __module__ = 'sds_image_matching_pb2'
  # @@protoc_insertion_point(class_scope:sds_image_matching.ImageMatching_Response)
  ))
_sym_db.RegisterMessage(ImageMatching_Response)



_IMAGEMATCHING = _descriptor.ServiceDescriptor(
  name='ImageMatching',
  full_name='sds_image_matching.ImageMatching',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=155,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='inference',
    full_name='sds_image_matching.ImageMatching.inference',
    index=0,
    containing_service=None,
    input_type=_IMAGEMATCHING_REQUEST,
    output_type=_IMAGEMATCHING_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEMATCHING)

DESCRIPTOR.services_by_name['ImageMatching'] = _IMAGEMATCHING

# @@protoc_insertion_point(module_scope)
