# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sds_damage_segmentation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sds_damage_segmentation.proto',
  package='sds_damage_segmentation',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dsds_damage_segmentation.proto\x12\x17sds_damage_segmentation\"\x1a\n\x07NDArray\x12\x0f\n\x07ndarray\x18\x01 \x01(\x0c\x32\\\n\x07Greeter\x12Q\n\tinference\x12 .sds_damage_segmentation.NDArray\x1a .sds_damage_segmentation.NDArray\"\x00\x62\x06proto3')
)




_NDARRAY = _descriptor.Descriptor(
  name='NDArray',
  full_name='sds_damage_segmentation.NDArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ndarray', full_name='sds_damage_segmentation.NDArray.ndarray', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['NDArray'] = _NDARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NDArray = _reflection.GeneratedProtocolMessageType('NDArray', (_message.Message,), dict(
  DESCRIPTOR = _NDARRAY,
  __module__ = 'sds_damage_segmentation_pb2'
  # @@protoc_insertion_point(class_scope:sds_damage_segmentation.NDArray)
  ))
_sym_db.RegisterMessage(NDArray)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='sds_damage_segmentation.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=86,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='inference',
    full_name='sds_damage_segmentation.Greeter.inference',
    index=0,
    containing_service=None,
    input_type=_NDARRAY,
    output_type=_NDARRAY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
