# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app.mod_service.sds_grpc.sds_damage_segmentation_pb2 as sds__damage__segmentation__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.inference = channel.unary_unary(
        '/sds_damage_segmentation.Greeter/inference',
        request_serializer=sds__damage__segmentation__pb2.NDArray.SerializeToString,
        response_deserializer=sds__damage__segmentation__pb2.NDArray.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def inference(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'inference': grpc.unary_unary_rpc_method_handler(
          servicer.inference,
          request_deserializer=sds__damage__segmentation__pb2.NDArray.FromString,
          response_serializer=sds__damage__segmentation__pb2.NDArray.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sds_damage_segmentation.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
