# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app.mod_service.sds_grpc.sds_removal_pb2 as sds__removal__pb2


class RemoverStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.inference = channel.unary_unary(
        '/sds_removal.Remover/inference',
        request_serializer=sds__removal__pb2.Request.SerializeToString,
        response_deserializer=sds__removal__pb2.Response.FromString,
        )


class RemoverServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def inference(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RemoverServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'inference': grpc.unary_unary_rpc_method_handler(
          servicer.inference,
          request_deserializer=sds__removal__pb2.Request.FromString,
          response_serializer=sds__removal__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sds_removal.Remover', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
